parameters:
#    gprs_client.example.class: gprs\ClientBundle\Example

services:
#    gprs_client.example:
#        class: %gprs_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
