<?php

namespace gprs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitProtesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends EntityRepository
{
    public function getAlarm($alarm)
    {
        $res = array();
        switch($alarm){
            case 'weight':
                $res = $this->getEntityManager()
                ->createQuery('SELECT a
                         FROM gprsAdminBundle:Alarm a
                         WHERE a.weight=1 and a.status=0
                         ')
                ->getArrayResult();
                break;
            default :
        }
        return $res;
    }
}
