<?php

namespace gprs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitProtesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    public function findLastService($icebox_id)
    {
        $res = $this->getEntityManager()
            ->createQuery('SELECT s
                     FROM gprsAdminBundle:Service s
                     WHERE s.icebox_id = '.$icebox_id.'
                     ORDER BY s.id DESC
                     ')
            ->setMaxResults(1)
            ->getResult();

        return isset($res[0]) ? $res[0] : false;
    }
}
