<?php

namespace gprs\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnitProtesterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraderRepository extends EntityRepository
{
    public function getTradersForAlarm($alarm)
    {
        $res = array();
        $field = 'alarm_weight';
        switch($alarm){
            case 'weight':
            case 'p1':
            case 'p2':
            case 'p3':
            case 'p4':
                $field = 'alarm_weight';
                break;
            case 'temperatura':
                $field = 'alarm_temperature';
                break;
            case 'power':
                $field = 'alarm_power';
                break;
            default :
        }
        $res = $this->getEntityManager()
            ->createQuery("SELECT t
                     FROM gprsAdminBundle:Trader t
                     WHERE t.$field=1
                     ")
            ->getArrayResult();
        
        return $res;
    }
}
