gprs\AdminBundle\Entity\Icebox:
  properties:
    image:
      - File:
          maxSize: 2048k
          maxSizeMessage: Please upload a image file not more than 2Mb
          mimeTypes: [image/gif, image/jpeg, image/pjpeg, image/png, image/tiff]
          mimeTypesMessage: Please upload a valid image file png, jpg, jpeg, gif or tiff formats