gprs\AdminBundle\Entity\Location:
  type:  entity
  table: location
  repositoryClass: gprs\AdminBundle\Entity\LocationRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    icebox_id:
      type: integer
    lat:
      type: float
      nullable: true
    lng:
      type: float
      nullable: true
    radius:
      type: integer
      nullable: true
    created_at:
      type: datetime
  lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
  manyToOne:
      icebox:
        targetEntity: Icebox
        joinColumn:
          name: icebox_id
          referencedColumnName: id
          onDelete: CASCADE