gprs\AdminBundle\Entity\Power:
  type:  entity
  table: power
  #repositoryClass: gprs\AdminBundle\Entity\PowerRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    icebox_id:
      type: integer
    count:
      type: float
      nullable: true
    created_at:
      type: datetime
  lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
  manyToOne:
      icebox:
        targetEntity: Icebox
        joinColumn:
          name: icebox_id
          referencedColumnName: id
          onDelete: CASCADE